#!/bin/sh

### BEGIN INIT INFO
# Provides:          checkkodi
# Required-Start:    $mediacenter $minidlna buttons
# Required-Stop:     
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Check kodi to diplay playing track
# Description:       Check kodi to diplay playing track

### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

NAME=checkkodi
DAEMON=/usr/local/bin/zorgbox/checkkodi.sh
DESC="Kodi playing tracks daemon"
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid

test -x $DAEMON || exit 5

if [ -f /etc/default/$NAME ] ; then
    . /etc/default/$NAME
fi

case "$1" in
    start)
	    log_daemon_msg "Starting $DESC" "$NAME"
	    touch /var/run/checkkodi.run
	    start-stop-daemon --start --quiet --pidfile $PIDFILE \
    	    --background --make-pidfile --startas $DAEMON -- $DAEMON_ARGS
        log_end_msg $?
    	;;
    stop)
    	log_daemon_msg "Stopping $DESC" "$NAME"
    	start-stop-daemon --oknodo --stop --quiet --pidfile $PIDFILE
	[ -f /var/run/checkkodi.run ] && rm /var/run/checkkodi.run
	echo "14:25:00 635.024902 T:2823357472   DEBUG: CAnnouncementManager - Announcement: OnTerminate from xbmc">>/home/osmc/.kodi/temp/kodi.log
	#sleep 1
	#ps aux| grep checkkodi.sh| grep -v grep|awk '{print $2}'|xargs kill -9
        log_end_msg $?
    	rm -f $PIDFILE
	    ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME
        ;;
    restart|reload|force-reload)
        $0 stop && sleep 2 && $0 start
	    ;;
    *)
    	echo "Usage: $0 {start|stop|status|restart|reload|force-reload}" >&2
	    exit 2
    	;;
esac

