#!/bin/sh
cat /etc/hosts| grep -v -i `hostname`>/tmp/$$.hosts
grep '"wlan0Mode": "hotspot"' /etc/zorgbox/network.json
if [ $? -eq 0 ] ; then
	echo 192.168.200.1 `hostname` >>/tmp/$$.hosts
else
	echo 127.0.0.1	`hostname` >>/tmp/$$.hosts
fi
mv /tmp/$$.hosts /etc/hosts
#service checkkodi restart

